-- MySQL Script generated by MySQL Workbench
-- Thu Oct 18 12:11:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sql7261794
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sql7261794
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql7261794` DEFAULT CHARACTER SET utf8 ;
USE `sql7261794` ;


-- -----------------------------------------------------
-- Table `sql7261794`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Patient` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Patient` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `address_home` VARCHAR(100) NOT NULL,
  `address_hospital` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql7261794`.`Medic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Medic` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Medic` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `age` INT NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `specialization` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sql7261794`.`Fitbit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Fitbit` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Fitbit` (
  `Patient_id` INT UNSIGNED NOT NULL,
  `timedate` VARCHAR(30) NOT NULL,
  `avg_heartbeats` INT NULL,
  `calories` INT NOT NULL,
  `elevation` DOUBLE NOT NULL,
  `floors` INT NOT NULL,
  `steps` INT NOT NULL,
  `distance` DOUBLE NOT NULL,
  `minutes_sleep` INT NOT NULL,
  `minutes_awake` INT NOT NULL,
  PRIMARY KEY (`Patient_id`, `timedate`),
  CONSTRAINT `fk_Fitbit_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `sql7261794`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql7261794`.`Hue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Hue` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Hue` (
  `Patient_id` INT UNSIGNED NOT NULL,
  `timedate` VARCHAR(30) NOT NULL,
  `cromoterapia` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Patient_id`, `timedate`),
  CONSTRAINT `fk_Hue_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `sql7261794`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql7261794`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Login` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Login` (
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `Patient_id` INT UNSIGNED NULL,
  `Medic_id` INT UNSIGNED NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `fk_Login_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `sql7261794`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Login_Medic1`
    FOREIGN KEY (`Medic_id`)
    REFERENCES `sql7261794`.`Medic` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `sql7261794`.`Medic_has_Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Medic_has_Patient` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Medic_has_Patient` (
  `Medic_id` INT UNSIGNED NOT NULL,
  `Patient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Medic_id`, `Patient_id`),
  CONSTRAINT `fk_Medic_has_Patient_Medic1`
    FOREIGN KEY (`Medic_id`)
    REFERENCES `sql7261794`.`Medic` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Medic_has_Patient_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `sql7261794`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql7261794`.`Message_Medic_Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Message_Medic_Patient` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Message_Medic_Patient` (
  `Medic_id` INT UNSIGNED NOT NULL,
  `Patient_id` INT UNSIGNED NOT NULL,
  `timedate` VARCHAR(30) NOT NULL,
  `medic_sender` BIT(1) NOT NULL DEFAULT 1,
  `message` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`Medic_id`, `Patient_id`, `timedate`),
  CONSTRAINT `fk_Medic_has_Patient1_Medic1`
    FOREIGN KEY (`Medic_id`)
    REFERENCES `sql7261794`.`Medic` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Medic_has_Patient1_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `sql7261794`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `sql7261794`.`Patient_Initial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Patient_Initial` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Patient_Initial` (
  `pregnancy_start_date` VARCHAR(20) NOT NULL,
  `weight` DOUBLE NOT NULL,
  `height` DOUBLE NOT NULL,
  `bmi` VARCHAR(20) NOT NULL,
  `twin` BIT(1) NOT NULL DEFAULT 0,
  `Patient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Patient_id`),
  CONSTRAINT `fk_Patient_Initial_Patient`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `sql7261794`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql7261794`.`Sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Sensor` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Sensor` (
  `Patient_id` INT UNSIGNED NOT NULL,
  `timedate` VARCHAR(30) NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `luminescence` DOUBLE NOT NULL,
  `humidity` DOUBLE NOT NULL,
  PRIMARY KEY (`Patient_id`, `timedate`),
  CONSTRAINT `fk_Sensor_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `sql7261794`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql7261794`.`Task_Activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Task_Activity` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Task_Activity` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Patient_id` INT UNSIGNED NOT NULL,
  `Medic_id` INT UNSIGNED NOT NULL,
  `date` VARCHAR(20) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `starting_program` BIT(1) NOT NULL DEFAULT 0,
  `executed` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `Patient_id`, `Medic_id`),
  CONSTRAINT `fk_Task_Activity_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `sql7261794`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Task_Activity_Medic1`
    FOREIGN KEY (`Medic_id`)
    REFERENCES `sql7261794`.`Medic` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql7261794`.`Task_Diet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Task_Diet` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Task_Diet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Patient_id` INT UNSIGNED NOT NULL,
  `Medic_id` INT UNSIGNED NOT NULL,
  `date` VARCHAR(20) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `starting_program` BIT(1) NOT NULL DEFAULT 0,
  `executed` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `Patient_id`, `Medic_id`),
  CONSTRAINT `fk_Task_Diet_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `sql7261794`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Task_Diet_Medic1`
    FOREIGN KEY (`Medic_id`)
    REFERENCES `sql7261794`.`Medic` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql7261794`.`Task_General`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Task_General` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Task_General` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Patient_id` INT UNSIGNED NOT NULL,
  `Medic_id` INT UNSIGNED NOT NULL,
  `date` VARCHAR(20) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `starting_program` BIT(1) NOT NULL DEFAULT 0,
  `executed` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `Patient_id`, `Medic_id`),
  CONSTRAINT `fk_Task_General_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `sql7261794`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Task_General_Medic1`
    FOREIGN KEY (`Medic_id`)
    REFERENCES `sql7261794`.`Medic` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql7261794`.`Weight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql7261794`.`Weight` ;

CREATE TABLE IF NOT EXISTS `sql7261794`.`Weight` (
  `Patient_id` INT UNSIGNED NOT NULL,
  `date` VARCHAR(20) NOT NULL,
  `weight` DOUBLE NOT NULL,
  PRIMARY KEY (`Patient_id`, `date`),
  CONSTRAINT `fk_Weight_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `sql7261794`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
